import React, { useState, useEffect } from 'react';
import Dashboard from './components/Dashboard';
import './App.css';

// Sample data - will be replaced with actual data files
const sampleData = {
  competitors: [
    { id: 'lendela', name: 'Lendela', type: 'aggregator', threat: 'high', lastUpdated: '2026-02-24' },
    { id: 'lendingbee', name: 'Lending Bee', type: 'direct', threat: 'high', lastUpdated: '2026-02-24' },
    { id: 'crawfort', name: 'Crawfort', type: 'direct', threat: 'critical', lastUpdated: '2026-02-24' },
    { id: 'credit21', name: 'Credit 21', type: 'direct', threat: 'medium', lastUpdated: '2026-02-24' },
    { id: 'moneykinetics', name: 'Money Kinetics', type: 'aggregator', threat: 'high', lastUpdated: '2026-02-24' },
    { id: 'roshi', name: 'Roshi', type: 'aggregator', threat: 'high', lastUpdated: '2026-02-24' },
    { id: 'lendingpot', name: 'Lendingpot', type: 'aggregator', threat: 'medium', lastUpdated: '2026-02-24' },
    { id: 'lendingcircle', name: 'Lending Circle', type: 'aggregator', threat: 'medium', lastUpdated: '2026-02-24' },
  ],
  dailyBriefings: [
    {
      date: '2026-02-24',
      summary: 'Crawfort pushing "8-minute approval" heavily. Lendela launched CNY campaign.',
      changes: 3,
      newAds: 5
    },
    {
      date: '2026-02-23',
      summary: 'Baseline established. 8 competitors tracked.',
      changes: 0,
      newAds: 0
    }
  ],
  adSnapshots: [
    { competitor: 'Crawfort', date: '2026-02-24', type: 'Image', message: 'Approved in 8 minutes', cta: 'Apply Now' },
    { competitor: 'Lendela', date: '2026-02-24', type: 'Video', message: 'Your 2025, Loan Matched', cta: 'Learn More' },
    { competitor: 'Lending Bee', date: '2026-02-24', type: 'Carousel', message: '1 Hour Approval', cta: 'Check Eligibility' },
  ]
};

function App() {
  const [activeTab, setActiveTab] = useState('overview');
  const [data, setData] = useState(sampleData);

  useEffect(() => {
    // Load actual data from JSON files if available
    fetch('./data/intel.json')
      .then(res => res.json())
      .then(setData)
      .catch(() => console.log('Using sample data'));
  }, []);

  return (
    <div className="app">
      <header className="header">
        <div className="logo">
          <span className="logo-icon">📊</span>
          <h1>PMAL Intelligence Dashboard</h1>
        </div>
        <nav className="nav">
          {['overview', 'competitors', 'ads', 'briefings', 'analysis'].map(tab => (
            <button
              key={tab}
              className={activeTab === tab ? 'active' : ''}
              onClick={() => setActiveTab(tab)}
            >
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
        </nav>
      </header>

      <main className="main">
        <Dashboard activeTab={activeTab} data={data} />
      </main>

      <footer className="footer">
        <p>Generated by Kimi Claw | PickMeALoan Competitive Intelligence</p>
        <p>Last updated: {new Date().toLocaleString('en-SG', { timeZone: 'Asia/Singapore' })} SGT</p>
      </footer>
    </div>
  );
}

export default App;